INSERT INTO EMPLOYEE (NAME, EMAIL) VALUES ('Pedro Alencar', 'pedro@gmail.com');
INSERT INTO EMPLOYEE (NAME, EMAIL) VALUES ('Gustavo Risatti', 'gustavo@gmail.com');
INSERT INTO EMPLOYEE (NAME, EMAIL) VALUES ('João da Silva', 'joao@gmail.com');
INSERT INTO EMPLOYEE (NAME, EMAIL) VALUES ('Maria Joaquina', 'maria@gmail.com');

INSERT INTO RESTAURANT (NAME) VALUES ('Restaurante Comida Baiana');
INSERT INTO RESTAURANT (NAME) VALUES ('Churrascaria Come Bem');
INSERT INTO RESTAURANT (NAME) VALUES ('Sushi do Shi');
INSERT INTO RESTAURANT (NAME) VALUES ('Boi na Brasa');
INSERT INTO RESTAURANT (NAME) VALUES ('Galeto a Primo Canto');

INSERT INTO VOTE (DATE_VOTE, STATUS) VALUES ('2022-12-19', 0);
INSERT INTO VOTE (DATE_VOTE, STATUS) VALUES ('2022-12-20', 0);
INSERT INTO VOTE (DATE_VOTE, STATUS) VALUES ('2022-12-21', 0);
INSERT INTO VOTE (DATE_VOTE, STATUS) VALUES ('2022-12-22', 0);

INSERT INTO VOTE_ITEM (EMPLOYEE_ID, RESTAURANT_ID, VOTE_ID) VALUES (1,1,1);
INSERT INTO VOTE_ITEM (EMPLOYEE_ID, RESTAURANT_ID, VOTE_ID) VALUES (2,1,1);
INSERT INTO VOTE_ITEM (EMPLOYEE_ID, RESTAURANT_ID, VOTE_ID) VALUES (3,1,1);
INSERT INTO VOTE_ITEM (EMPLOYEE_ID, RESTAURANT_ID, VOTE_ID) VALUES (4,3,1);

INSERT INTO VOTE_ITEM (EMPLOYEE_ID, RESTAURANT_ID, VOTE_ID) VALUES (1,1,2);
INSERT INTO VOTE_ITEM (EMPLOYEE_ID, RESTAURANT_ID, VOTE_ID) VALUES (2,2,2);
INSERT INTO VOTE_ITEM (EMPLOYEE_ID, RESTAURANT_ID, VOTE_ID) VALUES (3,2,2);
INSERT INTO VOTE_ITEM (EMPLOYEE_ID, RESTAURANT_ID, VOTE_ID) VALUES (4,3,2);

INSERT INTO VOTE_ITEM (EMPLOYEE_ID, RESTAURANT_ID, VOTE_ID) VALUES (1,1,3);
INSERT INTO VOTE_ITEM (EMPLOYEE_ID, RESTAURANT_ID, VOTE_ID) VALUES (2,1,3);
INSERT INTO VOTE_ITEM (EMPLOYEE_ID, RESTAURANT_ID, VOTE_ID) VALUES (3,1,3);
INSERT INTO VOTE_ITEM (EMPLOYEE_ID, RESTAURANT_ID, VOTE_ID) VALUES (4,3,3);

INSERT INTO VOTE_ITEM (EMPLOYEE_ID, RESTAURANT_ID, VOTE_ID) VALUES (1,1,4);
INSERT INTO VOTE_ITEM (EMPLOYEE_ID, RESTAURANT_ID, VOTE_ID) VALUES (2,3,4);
INSERT INTO VOTE_ITEM (EMPLOYEE_ID, RESTAURANT_ID, VOTE_ID) VALUES (3,3,4);
INSERT INTO VOTE_ITEM (EMPLOYEE_ID, RESTAURANT_ID, VOTE_ID) VALUES (4,3,4);